<?php
namespace App\Constants;
class General
{
    const WORKS = [ 
        'pics' => array(
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8051.jpg~2019/full/JUN_8051.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8055.jpg~2019/full/JUN_8055.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8057.jpg~2019/full/JUN_8057.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8061.jpg~2019/full/JUN_8061.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8063.jpg~2019/full/JUN_8063.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8065.jpg~2019/full/JUN_8065.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8068.jpg~2019/full/JUN_8068.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8069.jpg~2019/full/JUN_8069.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8072.jpg~2019/full/JUN_8072.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8092.jpg~2019/full/JUN_8092.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8099.jpg~2019/full/JUN_8099.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8112.jpg~2019/full/JUN_8112.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8113.jpg~2019/full/JUN_8113.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8140.jpg~2019/full/JUN_8140.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8147.jpg~2019/full/JUN_8147.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/JUN_8160.jpg~2019/full/JUN_8160.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/1.jpg~2019/full/1.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/2.jpg~2019/full/2.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/3.jpg~2019/full/3.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/4.jpg~2019/full/4.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/5.jpg~2019/full/5.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/6.jpg~2019/full/6.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/7.jpg~2019/full/7.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/8.jpg~2019/full/8.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/9.jpg~2019/full/9.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/10.jpg~2019/full/10.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/12.jpg~2019/full/12.jpg',
            'NCD Child~Global NCD Forum on Children and Youth~2019/11.jpg~2019/full/11.jpg',

            'Pink Caravan 2019~Pink Caravan Opening Conference 2019~2019/JUN_4643.jpg~2019/full/JUN_4643.jpg',
            'Pink Caravan 2019~Pink Caravan Opening Conference 2019~2019/JUN_4689.jpg~2019/full/JUN_4689.jpg',
            'Pink Caravan 2019~Pink Caravan Opening Conference 2019~2019/JUN_4712.jpg~2019/full/JUN_4712.jpg',
            'Pink Caravan 2019~Pink Caravan Opening Conference 2019~2019/JUN_4746.jpg~2019/full/JUN_4746.jpg',
            'Pink Caravan 2019~Pink Caravan Opening Conference 2019~2019/JUN_4772.jpg~2019/full/JUN_4772.jpg',
            'Pink Caravan 2019~Pink Caravan Opening Conference 2019~2019/JUN_4816.jpg~2019/full/JUN_4816.jpg',
            'Pink Caravan 2019~Pink Caravan Opening Conference 2019~2019/JUN_4893.jpg~2019/full/JUN_4893.jpg',
            'Pink Caravan 2019~Pink Caravan Opening Conference 2019~2019/JUN_4924.jpg~2019/full/JUN_4924.jpg',
            'Pink Caravan 2019~Pink Caravan (Sharjah) 2019~2019/JUN_5586.jpg~2019/full/JUN_5586.jpg',
            'Pink Caravan 2019~Pink Caravan (Sharjah) 2019~2019/JUN_5608.jpg~2019/full/JUN_5608.jpg',
            'Pink Caravan 2019~Pink Caravan (Sharjah) 2019~2019/JUN_5670.jpg~2019/full/JUN_5670.jpg',
            'Pink Caravan 2019~Pink Caravan (Sharjah) 2019~2019/JUN_5682.jpg~2019/full/JUN_5682.jpg',
            'Pink Caravan 2019~Pink Caravan (Sharjah) 2019~2019/JUN_5687.jpg~2019/full/JUN_5687.jpg',
            'Pink Caravan 2019~Pink Caravan (Sharjah) 2019~2019/JUN_5712.jpg~2019/full/JUN_5712.jpg',
            'Pink Caravan 2019~Pink Caravan (Sharjah) 2019~2019/JUN_5738.jpg~2019/full/JUN_5738.jpg',
            'Pink Caravan 2019~Pink Caravan (Sharjah) 2019~2019/JUN_5926.jpg~2019/full/JUN_5926.jpg',
            'Pink Caravan 2019~Pink Caravan (Sharjah) 2019~2019/JUN_5948.jpg~2019/full/JUN_5948.jpg',
            'Pink Caravan 2019~Pink Caravan (Sharjah) 2019~2019/JUN_5990.jpg~2019/full/JUN_5990.jpg',
            'Pink Caravan 2019~Pink Caravan (Dubai) 2019~2019/JUN_6019.jpg~2019/full/JUN_6019.jpg',
            'Pink Caravan 2019~Pink Caravan (Dubai) 2019~2019/JUN_6154.jpg~2019/full/JUN_6154.jpg',
            'Pink Caravan 2019~Pink Caravan (Dubai) 2019~2019/JUN_6156.jpg~2019/full/JUN_6156.jpg',
            'Pink Caravan 2019~Pink Caravan (Dubai) 2019~2019/JUN_6270.jpg~2019/full/JUN_6270.jpg',
            'Pink Caravan 2019~Pink Caravan (Dubai) 2019~2019/JUN_6298.jpg~2019/full/JUN_6298.jpg',
            'Pink Caravan 2019~Pink Caravan (Dubai) 2019~2019/JUN_6311.jpg~2019/full/JUN_6311.jpg',
            'Pink Caravan 2019~Pink Caravan (Dubai) 2019~2019/JUN_6336.jpg~2019/full/JUN_6336.jpg',
            'Pink Caravan 2019~Pink Caravan (Dubai) 2019~2019/JUN_6349.jpg~2019/full/JUN_6349.jpg',
            'Pink Caravan 2019~Pink Caravan (Dubai) 2019~2019/JUN_6462.jpg~2019/full/JUN_6462.jpg',
            'Pink Caravan 2019~Pink Caravan (Dubai) 2019~2019/JUN_6491.jpg~2019/full/JUN_6491.jpg',
            'Pink Caravan 2019~Pink Caravan (Dubai) 2019~2019/JUN_6493.jpg~2019/full/JUN_6493.jpg',
            'Pink Caravan 2019~Pink Caravan (Dubai) 2019~2019/JUN_6507.jpg~2019/full/JUN_6507.jpg',
            'Pink Caravan 2019~Pink Caravan (Dubai) 2019~2019/JUN_6526.jpg~2019/full/JUN_6526.jpg',
            'Pink Caravan 2019~Pink Caravan (Abu Dhabi) 2019~2019/JUN_6557.jpg~2019/full/JUN_6557.jpg',
            'Pink Caravan 2019~Pink Caravan (Abu Dhabi) 2019~2019/JUN_6652.jpg~2019/full/JUN_6652.jpg',
            'Pink Caravan 2019~Pink Caravan (Abu Dhabi) 2019~2019/JUN_6758.jpg~2019/full/JUN_6758.jpg',
            'Pink Caravan 2019~Pink Caravan (Abu Dhabi) 2019~2019/JUN_6762.jpg~2019/full/JUN_6762.jpg',
            'Pink Caravan 2019~Pink Caravan (Abu Dhabi) 2019~2019/JUN_6779.jpg~2019/full/JUN_6779.jpg',
            'Pink Caravan 2019~Pink Caravan (Abu Dhabi) 2019~2019/JUN_6920.jpg~2019/full/JUN_6920.jpg',
            'Pink Caravan 2019~Pink Caravan (Abu Dhabi) 2019~2019/JUN_6958.jpg~2019/full/JUN_6958.jpg',
            'Pink Caravan 2019~Pink Caravan (Abu Dhabi) 2019~2019/JUN_7111.jpg~2019/full/JUN_7111.jpg',
            'MenaLabs Management~Menalabs Kick-off 2019~2019/IMG_0867.jpg~2019/full/IMG_0867.jpg',
            'MenaLabs Management~Menalabs Kick-off 2019~2019/IMG_0873.jpg~2019/full/IMG_0873.jpg',
            'MenaLabs Management~Menalabs Kick-off 2019~2019/IMG_0898.jpg~2019/full/IMG_0898.jpg',
            'MenaLabs Management~Menalabs Kick-off 2019~2019/IMG_1009.jpg~2019/full/IMG_1009.jpg',
            'MenaLabs Management~Menalabs Kick-off 2019~2019/IMG_1014.jpg~2019/full/IMG_1014.jpg',
            'MenaLabs Management~Menalabs Kick-off 2019~2019/IMG_1096-3.jpg~2019/full/IMG_1096-3.jpg',
            'MenaLabs Management~Menalabs Kick-off 2019~2019/IMG_1108-2.jpg~2019/full/IMG_1108-2.jpg',
            'MenaLabs Management~Menalabs Kick-off 2019~2019/IMG_1134.jpg~2019/full/IMG_1134.jpg',
            'MenaLabs Management~Menalabs Kick-off 2019~2019/IMG_1179.jpg~2019/full/IMG_1179.jpg',



            'Pink Caravan~Pink Caravan Ride 2018 Press Conference~add-ppc1.jpg~full/add-ppc1.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Press Conference~add-ppc2.jpg~full/add-ppc2.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Press Conference~add-ppc3.jpg~full/add-ppc3.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Press Conference~add-ppc4.jpg~full/add-ppc4.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Opening Ceremony~add-poc1.jpg~full/add-poc1.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Opening Ceremony~add-poc2.jpg~full/add-poc2.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Opening Ceremony~add-poc3.jpg~full/add-poc3.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Opening Ceremony~add-poc4.jpg~full/add-poc4.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Opening Ceremony~add-poc5.jpg~full/add-poc5.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Opening Ceremony~add-poc6.jpg~full/add-poc6.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Opening Ceremony~add-poc7.jpg~full/add-poc7.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Opening Ceremony~add-poc8.jpg~full/add-poc8.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Opening Ceremony~add-poc9.jpg~full/add-poc9.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Opening Ceremony~add-poc10.jpg~full/add-poc10.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Closing Ceremony~pink-abudhabi-6.jpg~full/pink-abudhabi-6.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Closing Ceremony~pink-abudhabi-8.jpg~full/pink-abudhabi-8.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Closing Ceremony~pink-abudhabi-9.jpg~full/pink-abudhabi-9.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Closing Ceremony~add-pcc1.jpg~full/add-pcc1.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Closing Ceremony~add-pcc3.jpg~full/add-pcc3.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Closing Ceremony~add-pcc4.jpg~full/add-pcc4.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Closing Ceremony~add-pcc5.jpg~full/add-pcc5.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Closing Ceremony~pink-abudhabi-3.jpg~full/pink-abudhabi-3.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Closing Ceremony~6.jpg~full/6.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 Closing Ceremony~120.jpg~full/120.jpg',
            'Pink Caravan~Pink Caravan Ride 2018 ~pink-abudhabi-5.jpg~full/pink-abudhabi-5.jpg',
            'Pink Caravan~Pink Caravan Ride 2018  Roadshow Event~1.jpg~full/1.jpg',
            'Pink Caravan~Pink Caravan Ride 2018  Roadshow Event~3.jpg~full/3.jpg',
            'Pink Caravan~Pink Caravan Ride 2018  Roadshow Event~pink-dubai-2.jpg~full/pink-dubai-2.jpg',
            'Pink Caravan~Pink Caravan Ride 2018  Roadshow Event~add-alqudra1.jpg~full/add-alqudra1.jpg',
            'Pink Caravan~Pink Caravan Ride 2018  Roadshow Event~add-alqudra2.jpg~full/add-alqudra2.jpg',
            'Pink Caravan~Pink Caravan Ride 2018  Roadshow Event~add-alqudra3.jpg~full/add-alqudra3.jpg',
            'Pink Caravan~Pink Caravan Ride 2018  Roadshow Event~add-alqudra4.jpg~full/add-alqudra4.jpg',
            'Gulf Business Machine~Workshop~gbm-1.jpg~full/gbm-1.jpg',
            'Gulf Business Machine~Workshop~gbm-2.jpg~full/gbm-2.jpg',
            'Gulf Business Machine~Workshop~gbm-4.jpg~full/gbm-4.jpg',
            'Gulf Business Machine~Workshop~gbm-5.jpg~full/gbm-5.jpg',
            'Gulf Business Machine~Workshop~gbm-6.jpg~full/gbm-6.jpg',
            'Gulf Business Machine~Workshop~gbm-7.jpg~full/gbm-7.jpg',
            'Gulf Business Machine~Exhibition Booth~gbm-8.jpg~full/gbm-8.jpg',
            'Gulf Business Machine~Exhibition Booth~gbm-3.jpg~full/gbm-3.jpg',
            'Gulf Business Machine~Exhibition Booth~gbm-9.jpg~full/gbm-9.jpg',
            'Gulf Business Machine~Workshop~add-gbm1.jpg~full/add-gbm1.jpg',
            'Gulf Business Machine~Workshop~add-gbm2.jpg~full/add-gbm2.jpg',
            'Gulf Business Machine~Workshop~add-gbm3.jpg~full/add-gbm3.jpg',
            'Canon Middle East ~World Art Dubai ~add-01.jpg~full/add-01.jpg',
            'Canon Middle East ~World Art Dubai ~canon-3.jpg~full/canon-3.jpg',
            'Canon Middle East ~World Art Dubai ~canon-6.jpg~full/canon-6.jpg',
            'Canon Middle East ~World Art Dubai ~add-wad2017-1.jpg~full/add-wad2017-1.jpg',
            'Canon Middle East ~World Art Dubai ~add-wad2017-2.jpg~full/add-wad2017-2.jpg',
            'Canon Middle East ~World Art Dubai ~add-wad2017-3.jpg~full/add-wad2017-3.jpg',
            'Canon Middle East ~World Art Dubai ~add-wad2017-4.jpg~full/add-wad2017-4.jpg',
            'Canon Middle East ~World Art Dubai ~add-wad2017-5.jpg~full/add-wad2017-5.jpg',
            'Canon Middle East ~World Art Dubai ~add-wad2017-6.jpg~full/add-wad2017-6.jpg',
            'Canon Middle East ~World Art Dubai ~add-wad2017-7.jpg~full/add-wad2017-7.jpg',
            'Canon Middle East ~World Art Dubai ~add-wad2017-8.jpg~full/add-wad2017-8.jpg',
            'Friends Of Cancer Patients (FOCP)~Kick Cancer Press Launch~p-3.jpg~full/p-3.jpg',
            'Friends Of Cancer Patients (FOCP)~Kick Cancer Press Launch~kick-cancer-1.jpg~full/kick-cancer-1.jpg',
            'Friends Of Cancer Patients (FOCP)~Kick Cancer Press Launch~kick-cancer-2.jpg~full/kick-cancer-2.jpg',
            'Friends Of Cancer Patients (FOCP)~Kick Cancer Press Launch~add-kc1.jpg~full/add-kc1.jpg',
            'Friends Of Cancer Patients (FOCP)~Kick Cancer Press Launch~add-kc2.jpg~full/add-kc2.jpg',
            'Friends Of Cancer Patients (FOCP)~Kick Cancer Press Launch~add-kc3.jpg~full/add-kc3.jpg',
            'Friends Of Cancer Patients (FOCP)~Kick Cancer Press Launch~add-kc5.jpg~full/add-kc5.jpg',
            'MenaLabs Management~Exhibition stand at Arab Health~menalabs-3.jpg~full/menalabs-3.jpg',
            'MenaLabs Management~Exhibition stand at Arab Health~menalabs-4.jpg~full/menalabs-4.jpg',
            'MenaLabs Management~Exhibition stand at Arab Health~menalabs-5.jpg~full/menalabs-5.jpg',
            'MenaLabs Management~Exhibition stand at MedLab~menalabs-6.jpg~full/menalabs-6.jpg',
            'MenaLabs Management~Exhibition stand at MedLab~menalabs-7.jpg~full/menalabs-7.jpg',
            'MenaLabs Management~Menalabs Website~menalabs-desktop.jpg~full/menalabs-desktop.jpg',
            'MenaLabs Management~Menalabs Website (Responsive)~menalabs-laptop.jpg~full/menalabs-laptop.jpg',
            'NAMA Women Advancement Establishment~Women Economic Empowerment Global Summit Reception Dinner~nama-2.jpg~full/nama-2.jpg',
            'NAMA Women Advancement Establishment~Women Economic Empowerment Global Summit Reception Dinner~add-nama1.jpg~full/add-nama1.jpg',
            'NAMA Women Advancement Establishment~Women Economic Empowerment Global Summit Reception Dinner~add-nama2.jpg~full/add-nama2.jpg',
            'NAMA Women Advancement Establishment~Women Economic Empowerment Global Summit Reception Dinner~nama-3.jpg~full/nama-3.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 Breakfast Meeting~ncd-5.jpg~full/ncd-5.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 Breakfast Meeting~ncd-6.jpg~full/ncd-6.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 ~4.jpg~full/4.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 ~5.jpg~full/5.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 ~ncd-4.jpg~full/ncd-4.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 ~ncd-7.jpg~full/ncd-7.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 ~add-ncd1.jpg~full/add-ncd1.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 ~add-ncd4.jpg~full/add-ncd4.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 ~add-ncd5.jpg~full/add-ncd5.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 ~add-ncd6.jpg~full/add-ncd6.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 ~add-ncd7.jpg~full/add-ncd7.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 ~add-ncd9.jpg~full/add-ncd9.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 Workshops~ncd-1.jpg~full/ncd-1.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 Workshops~ncd-2.jpg~full/ncd-2.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 Workshops~ncd-3.jpg~full/ncd-3.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 Workshops~add-ncd2.jpg~full/add-ncd2.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 Workshops~add-ncd3.jpg~full/add-ncd3.jpg',
            'NCD Alliance~Global NCD Alliance Forum 2017 Reception Dinner~add-ncd8.jpg~full/add-ncd8.jpg',
            '~~oracle-2.jpg~full/oracle-2.jpg',
            'Oracle ~Workshop ~oracle-1.jpg~full/oracle-1.jpg',
            'Oracle ~Workshop~add-08.jpg~full/add-08.jpg',
            'Oracle ~Workshop~add-09.jpg~full/add-09.jpg',
            'Oracle ~Workshop~add-19.jpg~full/add-19.jpg',
            'Oracle ~Workshop~add-20.jpg~full/add-20.jpg',
            'Oracle ~Workshop~add-21.jpg~full/add-21.jpg',
            'Oracle ~Workshop~add-05.jpg~full/add-05.jpg',
            'MenaLabs Management~Microsite~menalabs-microsite.jpg~full/menalabs-microsite.jpg',
            'MenaLabs Management~Microsite~menalabs-microsite2.jpg~full/menalabs-microsite2.jpg',
            'CBRE~Promotional Stand at Dalma Mall Abu Dhabi~cbre-1.jpg~full/cbre-1.jpg',
            'CBRE~Promotional Stand at Dalma Mall Abu Dhabi~cbre-2.jpg~full/cbre-2.jpg',
            'CBRE~Promotional Stand at Dalma Mall Abu Dhabi~cbre-3.jpg~full/cbre-3.jpg',
            'CBRE~Promotional Stand at Dalma Mall Abu Dhabi~cbre-4.jpg~full/cbre-4.jpg',
            'CBRE~Promotional Stand at Dalma Mall Abu Dhabi~cbre-5.jpg~full/cbre-5.jpg',
            '~~p-5.jpg~full/p-5.jpg',
            'Canon Middle East ~Walk For A Cause Abu Dhabi~canon-10.jpg~full/canon-10.jpg',
            'Canon Middle East ~Walk For A Cause Abu Dhabi~canon-11.jpg~full/canon-11.jpg',
            'Canon Middle East ~Walk For A Cause Abu Dhabi~canon-13.jpg~full/canon-13.jpg',
            'Canon Middle East ~Walk For A Cause Abu Dhabi~canon-14.jpg~full/canon-14.jpg',
            'Canon Middle East ~Walk For A Cause Abu Dhabi~canon-12.jpg~full/canon-12.jpg',
            '~~p-1.jpg~full/p-1.jpg',
            'ICD Brookfield ~ICD-Brookfield Place Dubai Ground breaking~icd-1.jpg~full/icd-1.jpg',
            'ICD Brookfield ~ICD-Brookfield Place Dubai Ground breaking~icd-2.jpg~full/icd-2.jpg',
            'ICD Brookfield ~ICD-Brookfield Place Dubai Ground breaking~icd-3.jpg~full/icd-3.jpg',
            'Genetika~Genetika Website~genetika-desktop.jpg~full/genetika-desktop.jpg',
            'Genetika~Genetika Website (Responsive)~genetika-laptop.jpg~full/genetika-laptop.jpg',
            'Canon Middle East ~Recycling Initiative with Dubai Municipality~add-canon-recycle1.jpg~full/add-canon-recycle1.jpg',
            'Canon Middle East ~Recycling Initiative with Dubai Municipality~add-canon-recycle2.jpg~full/add-canon-recycle2.jpg',
            'Canon Middle East ~Recycling Initiative with Dubai Municipality~add-canon-recycle3.jpg~full/add-canon-recycle3.jpg',
            '~~p-14.jpg~full/p-14.jpg',
            'LinkedIn~Christmas Party~christmas1.jpg~full/christmas1.jpg',
            'LinkedIn~Christmas Party~christmas2.jpg~full/christmas2.jpg',
            'LinkedIn~Christmas Party~christmas3.jpg~full/christmas3.jpg',
            'LinkedIn~Christmas Party~christmas4.jpg~full/christmas4.jpg',
            'Dubai Dance Out~Launch Event~add-10.jpg~full/add-10.jpg',
            'Dubai Dance Out~Launch Event~add-11.jpg~full/add-11.jpg',
            'Dubai Dance Out~Launch Event~add-12.jpg~full/add-12.jpg',
            'Dubai Dance Out~Launch Event~add-13.jpg~full/add-13.jpg',
            'Dubai Dance Out~Launch Event~add-15.jpg~full/add-15.jpg',
            'Canon Middle East ~Earth Hour Dubai ~add-03.jpg~full/add-03.jpg',
            'Canon Middle East ~Earth Hour Dubai ~add-canon-earthhour1.jpg~full/add-canon-earthhour1.jpg',
            'Canon Middle East ~Earth Hour Dubai ~add-07.jpg~full/add-07.jpg',
            'Canon Middle East ~Earth Hour Dubai ~add-canon-earthhour2.jpg~full/add-canon-earthhour2.jpg',
            'MenaLabs Management~Menalabs Annual Kick Off ~add-menalabs-alhamra1.jpg~full/add-menalabs-alhamra1.jpg',
            'MenaLabs Management~Menalabs Annual Kick Off ~add-menalabs-alhamra2.jpg~full/add-menalabs-alhamra2.jpg',
            'MenaLabs Management~Menalabs Annual Kick Off ~add-menalabs-alhamra3.jpg~full/add-menalabs-alhamra3.jpg',
            'MenaLabs Management~Menalabs Kick Off ~menalabs-ko-4.jpg~full/menalabs-ko-4.jpg',
            'MenaLabs Management~Menalabs Annual Kick Off ~menalabs-ko-1.jpg~full/menalabs-ko-1.jpg',
            'MenaLabs Management~Menalabs Annual Kick Off ~menalabs-ko-2.jpg~full/menalabs-ko-2.jpg',
            'Canon Middle East ~Showroom Inauguration Abu Dhabi~add-cso1.jpg~full/add-cso1.jpg',
            'Canon Middle East ~Showroom Inauguration Abu Dhabi~add-cso2.jpg~full/add-cso2.jpg',
            'Canon Middle East ~Showroom Inauguration Abu Dhabi~add-cso4.jpg~full/add-cso4.jpg',
            'Canon Middle East ~Showroom Inauguration Abu Dhabi~add-cso5.jpg~full/add-cso5.jpg',
            'Canon Middle East ~Showroom Inauguration Abu Dhabi~add-cso3.jpg~full/add-cso3.jpg',
            'Canon Middle East ~Special Olympics Middle East and North Africa (MENA) Regional Games~add-canon-so1.jpg~full/add-canon-so1.jpg',
            'Canon Middle East ~Special Olympics Middle East and North Africa (MENA) Regional Games~add-canon-so2.jpg~full/add-canon-so2.jpg',
            'Canon Middle East ~Standard Chartered Marathon 2018~add-cscm1.jpg~full/add-cscm1.jpg',
            'Canon Middle East ~Standard Chartered Marathon 2018~add-cscm2.jpg~full/add-cscm2.jpg',
            'Canon Middle East ~Standard Chartered Marathon 2018~add-cscm3.jpg~full/add-cscm3.jpg',
            'Canon Middle East ~Standard Chartered Marathon 2018~add-cscm4.jpg~full/add-cscm4.jpg',
            'Canon Middle East ~Standard Chartered Marathon 2018~add-cscm5.jpg~full/add-cscm5.jpg',
            'Canon Middle East ~Standard Chartered Marathon 2018~2.jpg~full/2.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Press Conference~139.jpg~full/139.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Press Conference~153.jpg~full/153.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Press Conference~154.jpg~full/154.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Press Conference~169.jpg~full/169.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Press Conference~170.jpg~full/170.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Press Conference~179.jpg~full/179.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Press Conference~184.jpg~full/184.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Opening Ceremony~187.jpg~full/187.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Opening Ceremony~189.jpg~full/189.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Opening Ceremony~048.jpg~full/048.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Opening Ceremony~049.jpg~full/049.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Opening Ceremony~037.jpg~full/037.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Opening Ceremony~047.jpg~full/047.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Closing Ceremony~185.jpg~full/185.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Closing Ceremony~193.jpg~full/193.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Closing Ceremony~194.jpg~full/194.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 Closing Ceremony~186.jpg~full/186.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 in the Press~190.jpg~full/190.jpg',
            'Pink Caravan~Pink Caravan Ride 2017 in the Press~191.jpg~full/191.jpg',
            'Linkedln~Dubai Office Inauguration~add-04.jpg~full/add-04.jpg',
            'Linkedln~Dubai Office Inauguration~add-linkedln.jpg~full/add-linkedln.jpg',
            'Linkedln~Dubai Office Inauguration~add-16.jpg~full/add-16.jpg',
            'Linkedln~Dubai Office Inauguration~add-17.jpg~full/add-17.jpg',
            'Linkedln~Dubai Office Inauguration~add-18.jpg~full/add-18.jpg',
            'Canon Middle East ~Blood Donation Drive~canon-26.jpg~full/canon-26.jpg',
            'Canon Middle East ~Blood Donation Drive~add-canon-bd1.jpg~full/add-canon-bd1.jpg',
            'Canon Middle East ~Blood Donation Drive~add-02.jpg~full/add-02.jpg',
            'Canon Middle East ~Blood Donation Drive~canon-28.jpg~full/canon-28.jpg',
            'Canon Middle East ~American School of Dubai Activation~canon-30.jpg~full/canon-30.jpg',
            '~~p-4.jpg~full/p-4.jpg',
            'Canon Middle East ~American School of Dubai Activation~canon-29.jpg~full/canon-29.jpg',
            'Canon Middle East ~American School of Dubai Activation~canon-31.jpg~full/canon-31.jpg',
            'Diagnostika~E-Commerce Website~diagnostika-desktop.jpg~full/diagnostika-desktop.jpg',
            'Diagnostika~E-Commerce Website (Responsive)~diagnostika-laptop.jpg~full/diagnostika-laptop.jpg',


            )];	
}

